pihole:
  hosts:
    artemis:
      ansible_host: 192.168.7.10
      ansible_user: pi
      ansible_python_interpreter: /usr/bin/python3

    apollo:
      ansible_host: 192.168.7.11
      ansible_user: pi
      ansible_python_interpreter: /usr/bin/python3
    
docker:
  hosts:
    hestia:
      ansible_host: 192.168.30.31
      ansible_user: ubuntu

    hermes:
      ansible_host: 192.168.30.32
      ansible_user: ubuntu

    dionysus:
      ansible_host: 192.168.30.33
      ansible_user: ubuntu

    demeter:
      ansible_host: 192.168.30.34
      ansible_user: ubuntu

    tartarus:
      ansible_host: 192.168.30.35
      ansible_user: ubuntu

init:
  hosts:  
    intital:
      ansible_host: 192.168.10.104