http:
  routers:
    raklora:
      entryPoints:
        - "https"
      rule: "Host(`rak.iot.lontiotlabs.au`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: raklora
    milesight:
      entryPoints:
        - "https"
      rule: "Host(`milesight.iot.lontiotlabs.au`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: milesight
    tablet:
      entryPoints:
        - "https"
      rule: "Host(`tablet.iot.lontiotlabs.au`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: tablet
    zigbee:
      entryPoints:
        - "https"
      rule: "Host(`zigbee.iot.lontiotlabs.au`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: zigbee
    zigbee2mqtt:
      entryPoints:
        - "https"
      rule: "Host(`zigbee2mqtt.iot.lontiotlabs.au`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: zigbee2mqtt

  services:
    raklora:
      loadBalancer:
        servers:
          - url: "http://192.168.10.10"
        passHostHeader: true
    milesight:
      loadBalancer:
        servers:
          - url: "https://192.168.10.11"
        passHostHeader: true
    tablet:
      loadBalancer:
        servers:
          - url: "http://192.168.10.3:2323"
        passHostHeader: true
    zigbee:
      loadBalancer:
        servers:
          - url: "http://192.168.10.8"
        passHostHeader: true
    zigbee2mqtt:
      loadBalancer:
        servers:
          - url: "http://192.168.10.5:8080"
        passHostHeader: true